apiVersion: apps/v1
kind: Deployment
metadata:
  name: allinone
  labels:
    app.kubernetes.io/name: allinone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: allinone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: allinone
    spec:
      hostname: slurmctl
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeName: node
      containers:
      - name: allinone
        imagePullPolicy: Always
        image: 10.67.125.196:5000/all-in-one:1.1
        command: ["/bin/sh", "-c"]
        args: [ "/workspace/start_llm.sh && /tini -- /usr/local/bin/docker-entrypoint.sh"]
        volumeMounts:
          - mountPath: /var/fastchat 
            name: results
          - mountPath: "/tmp"
            name: job-result
        ports:
        - name: chatfile
          containerPort: 8080
        - name: munge
          containerPort: 80
        - name: chatapi
          containerPort: 8000
        - name: slurmrestd
          containerPort: 6820
        - name: slurmctld
          containerPort: 6817
        securityContext:
          allowPrivilegeEscalation: true
      volumes:
        - name: results
          hostPath:
            path: /var/fastchat      # node path, must contains llm model
            type: DirectoryOrCreate 
        - name: job-result
          hostPath:
            path: /nfs/data      # node path, must contains llm model
            type: Directory
 
---
apiVersion: v1
kind: Service
metadata:
  name: slurmctl
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: allinone
  ports:
    - port: 6820
      targetPort: 6820
        #nodePort: 6820
      name: slurmrestd
    - port: 8080
      # nodePort: 8080
      targetPort: 8080
      name: chatfile
    - port: 6817
      nodePort: 30001
      targetPort: 6817
      name: slurmctld
    - port: 80
      nodePort: 30002
      targetPort: 80
      name: munge